### ISSUE TITLE
Link from Exercise 1 to CSV data goes to Github csv viewer 

### ISSUE THREAD

**Issue by andrewphilipsmith** [antonys/antonys.github.io#1]
The current link (https://github.com/antonys/antonys.github.io/blob/master/downloads/ActivityInfo_Export_Fri_May_02_08-34-22_GeONG.csv) in Exercise 1 (http://antonys.github.io/qgis-workshop/exercises/load_data.html) to CSV data goes to Github csv viewer. 

To allow direct download of CSV data change replace the link with:
https://antonys.github.io/downloads/ActivityInfo_Export_Fri_May_02_08-34-22_GeONG.csv

**Comment by antonys** [comment]
Resolved
